pipeline {
    agent any 

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning repository...'
                git branch: "main", url: "https://github.com/sergiorope/microlibrary"
            }
        }
        
        stage('Build Customer Service') {
            steps {
                dir("businessdomain/customer") {
                    bat 'mvn clean package'
                }
            }
        }
        
        stage('Remove Old Customer Docker Image') {
            steps {
                bat "docker rmi -f sergiorodper/microlibrary:microlibrary-customer-v1 || echo 'No existing image to remove for customer'"
            }
        }

        stage('Build Docker Image for Customer') {
            steps {
                dir("businessdomain/customer") {
                    bat 'docker build -t sergiorodper/microlibrary:microlibrary-customer-v1 --no-cache --build-arg JAR_FILE=target/*.jar .'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir(".") {
                    bat 'echo Current directory: %cd%'
                    bat 'docker-compose down'
                    bat 'docker-compose up -d --remove-orphans'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
