apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk 
  MYSQL_USER: bXlzcWw=                 
  MYSQL_PASSWORD: cXdlcnR5  