server.port=8088
spring.application.name=keycloack
spring.cloud.config.enabled=false  

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER:http://localhost:8252/eureka}
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true


keycloak.base-uri=${KEYCLOAK_SERVER:http://localhost:8091/realms/}
keycloak.authorization-uri=${keycloak.base-uri}microlibrary/protocol/openid-connect/auth
keycloak.user-info-uri=${keycloak.base-uri}microlibrary/protocol/openid-connect/userinfo
keycloak.token-uri=${keycloak.base-uri}microlibrary/protocol/openid-connect/token
keycloak.logout=${keycloak.base-uri}microlibrary/protocol/openid-connect/logout
keycloak.jwk-set-uri=${keycloak.base-uri}microlibrary/protocol/openid-connect/certs
keycloak.certs-id=${KEYCLOAK_REAL_ID:2cc56733-92a7-43e1-925b-7f3ddf27c467}

keycloak.client-id=microlibrary-app
keycloak.client-secret=qwerty
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO
