apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-config
data:
  DB_HOST: mysql-service       # Nombre del servicio MySQL en el clúster
  DB_PORT: "3306"              # Puerto en el que MySQL escucha
  DB_NAME: my_database         # Nombre de la base de datos
  DB_USER: my_user             # Nombre de usuario para la conexión
  DB_PASSWORD: my_password     # Contraseña para la conexión
