apiVersion: v1
kind: ConfigMap
metadata:
  name: loanline-config
data:
  application.properties: |
      spring.application.name: microlibrary-loanline
      springdoc.swagger-ui.enabled: "true"
      server.port: "0"
      springdoc.packagesToScan: com.microlibrary.loanline.entities, com.microlibrary.loanline.controller
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      eureka.client.register-with-eureka: "true"
      eureka.client.healthcheck.enabled: "true"
      eureka.client.fetch-registry: "true"
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      spring.jpa.hibernate.ddl-auto: update
      spring.jpa.show-sql: "true"
      spring.datasource.url: jdbc:mysql://mysql_db:3306/loanline
