apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  SPRING_APPLICATION_NAME: microlibrary-product
  SPRINGDOC_SWAGGER_UI_ENABLED: "true"
  SERVER_PORT: "0"
  SPRINGDOC_PACKAGES_TO_SCAN: "com.microlibrary.product.entities, com.microlibrary.product.controller"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_HEALTHCHECK_ENABLED: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/product
