apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanline-deployment
  labels:
    app: loanline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanline
  template:
    metadata:
      labels:
        app: loanline
    spec:
      containers:
        - name: loanline
          image: sergiorodper/microlibrary:microlibrary-loanline-v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: loanline-config  
            - secretRef:
                name: loanline-secret

