apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sergiorodper/microlibrary:microlibrary-product-v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: product-config   
            - secretRef:
                name: product-secret   
          ports:
            - containerPort: 8185  # Puerto donde el contenedor escuchará
