apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deployment
  labels:
    app: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: sergiorodper/microlibrary:microlibrary-loan-v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: loan-config
            - secretRef:
                name: loan-secret
