apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: sergiorodper/microlibrary:microlibrary-customer-v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: customer-config  
            - secretRef:
                name: customer-secret 
     
