apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sergiorodper/microlibrary:microlibrary-product-v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mysql-service  # Nombre del servicio de MySQL en el cluster Kubernetes
          envFrom:
            - configMapRef:
                name: product-config   # ConfigMap que contiene configuraciones como DB_HOST, etc.
            - secretRef:
                name: product-secret   # Secret que contiene credenciales como contraseñas, etc.
