apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: sergiorodper/microlibrary:microlibrary-eurekaServer-v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: eureka-config  

