apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka  
  ports:
    - protocol: TCP
      port: 8252       
      targetPort: 8252  
  clusterIP: None        
