apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  ports:
    - port: 8080  
      targetPort: 8080  
  selector:
    app: product  
  type: ClusterIP  
